// Pure local file system storage adapter - no database operations
import { writeFile, mkdir, unlink, stat, readdir } from 'fs/promises';
import { join, dirname, resolve, basename } from 'path';
import type {
	StorageAdapter,
	StorageConfig,
	UploadFileData,
	StorageFile
} from '../interfaces/storage';
import { cmsLogger } from '../../utils/logger';

const DEFAULT_MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB

/**
 * Pure local file system storage adapter - only handles files
 */
export class LocalStorageAdapter implements StorageAdapter {
	readonly name = 'local';
	private config: Required<StorageConfig>;

	constructor(config: StorageConfig) {
		this.config = {
			basePath: config.basePath,
			baseUrl: config.baseUrl || '',
			maxFileSize: config.maxFileSize || DEFAULT_MAX_FILE_SIZE,
			options: config.options || {}
		};
	}

	/** See {@link StorageAdapter.setMaxFileSize}. */
	setMaxFileSize(bytes: number): void {
		if (Number.isFinite(bytes) && bytes > 0) this.config.maxFileSize = bytes;
	}

	/**
	 * Strip path traversal sequences, keeping only the base filename.
	 */
	private sanitizeFilename(filename: string): string {
		return basename(filename).replace(/^\.+/, '_');
	}

	/**
	 * Generate unique filename preserving original name
	 */
	private async generateUniqueFilename(originalFilename: string): Promise<string> {
		const safe = this.sanitizeFilename(originalFilename);
		const { name, ext } = this.parseFilename(safe);
		let filename = safe;
		let counter = 1;

		// Check if file exists on disk
		while (await this.fileExistsOnDisk(filename)) {
			filename = `${name} (${counter})${ext}`;
			counter++;
		}

		return filename;
	}

	/**
	 * Parse filename into name and extension
	 */
	private parseFilename(filename: string): { name: string; ext: string } {
		const lastDotIndex = filename.lastIndexOf('.');
		if (lastDotIndex === -1) {
			return { name: filename, ext: '' };
		}
		return {
			name: filename.substring(0, lastDotIndex),
			ext: filename.substring(lastDotIndex)
		};
	}

	/**
	 * Check if file exists on disk
	 */
	private async fileExistsOnDisk(filename: string): Promise<boolean> {
		try {
			const filePath = join(this.config.basePath, filename);
			await stat(filePath);
			return true;
		} catch {
			return false;
		}
	}

	/**
	 * Store a file and return storage info
	 */
	async store(data: UploadFileData): Promise<StorageFile> {
		// Validate file size
		if (data.size > this.config.maxFileSize) {
			throw new Error(
				`File too large: ${data.size} bytes. Maximum size: ${this.config.maxFileSize} bytes`
			);
		}

		// An explicit key is authoritative — the caller owns uniqueness and wants
		// a predictable location (e.g. `{assetId}/original.png`, so variants can
		// be written alongside it). Otherwise fall back to deriving a
		// non-colliding name from the original filename.
		const key = data.key
			? this.sanitizeKey(data.key)
			: await this.generateUniqueFilename(data.filename);
		const filePath = join(this.config.basePath, key);

		// Store internal path only - URL will be generated by API with asset ID
		// This forces all access through /assets/{id} for proper authorization
		const url = ''; // Will be populated as /assets/{assetId}/{filename} by the API

		cmsLogger.debug('[LocalStorageAdapter] Storing file:', {
			key,
			filePath,
			note: 'URL will be generated as /assets/{assetId}/{filename}',
			basePath: this.config.basePath
		});

		// Ensure storage directory exists
		await mkdir(dirname(filePath), { recursive: true });

		// Save file to disk
		await writeFile(filePath, data.buffer);

		return {
			key,
			path: filePath,
			url, // Empty - API will generate clean URL with asset ID
			size: data.size
		};
	}

	/**
	 * Make a caller-supplied key safe to join onto `basePath`.
	 *
	 * Keys may contain `/` — that's the point, `{assetId}/original.png` is a
	 * directory and a file. What they may not do is climb out of the storage
	 * root, so each segment is stripped of traversal and empty segments are
	 * dropped. A key that sanitizes to nothing falls back to the raw basename.
	 */
	private sanitizeKey(key: string): string {
		const segments = key
			.split('/')
			.map((segment) => basename(segment).replace(/^\.+/, '_'))
			.filter((segment) => segment.length > 0 && segment !== '.' && segment !== '..');
		return segments.length > 0 ? segments.join('/') : this.sanitizeFilename(key);
	}

	/**
	 * Resolve a path and prove it stays inside `basePath`, or throw.
	 *
	 * Every read/write entry point funnels through here. Keeping one copy is a
	 * safety property, not tidiness: this is the only thing standing between a
	 * caller-influenced path and the rest of the filesystem, and a
	 * per-call-site copy is how one of them ends up missing the check.
	 */
	private assertWithinBase(path: string): string {
		const resolved = resolve(path);
		const base = resolve(this.config.basePath);
		if (!resolved.startsWith(base + '/') && resolved !== base) {
			throw new Error('Access denied: path outside storage directory');
		}
		return resolved;
	}

	/**
	 * Where a key lives on disk. Mirrors what `store()` reports, for callers
	 * holding a key that never went through it.
	 */
	resolvePath(key: string): string {
		return join(this.config.basePath, this.sanitizeKey(key));
	}

	/**
	 * Read a file from storage
	 * Used by API endpoint to serve files
	 */
	async getObject(path: string): Promise<Buffer> {
		const resolved = this.assertWithinBase(path);
		const { readFile } = await import('fs/promises');
		return await readFile(resolved);
	}

	/**
	 * Read a file from storage as a stream.
	 *
	 * Same containment check as `getObject` — a streaming read is still a read,
	 * and skipping the check here would reintroduce the traversal escape on the
	 * path callers now prefer.
	 */
	async getStream(path: string): Promise<ReadableStream<Uint8Array>> {
		const resolved = this.assertWithinBase(path);
		const { createReadStream } = await import('fs');
		const { Readable } = await import('stream');
		// Surface a missing file as a rejected promise, matching getObject —
		// otherwise the error would only appear mid-stream, after headers had
		// already been sent and the status code was no longer changeable.
		await stat(resolved);
		return Readable.toWeb(createReadStream(resolved)) as ReadableStream<Uint8Array>;
	}

	/**
	 * Delete a file from storage
	 */
	async delete(path: string): Promise<boolean> {
		try {
			await unlink(this.assertWithinBase(path));
			return true;
		} catch (error) {
			cmsLogger.warn('Could not delete file from disk:', error);
			return false;
		}
	}

	/**
	 * Check if file exists
	 */
	async exists(path: string): Promise<boolean> {
		try {
			await stat(this.assertWithinBase(path));
			return true;
		} catch {
			// Covers both "outside the base" and "not there" — `exists` reports a
			// boolean either way, so the distinction has no caller.
			return false;
		}
	}

	/**
	 * Get public URL for a file path
	 */
	getUrl(path: string): string {
		// Extract filename from path and construct URL
		const filename = path.split('/').pop() || '';
		return `${this.config.baseUrl}/${encodeURIComponent(filename)}`;
	}

	/**
	 * Get storage information
	 */
	async getStorageInfo(): Promise<{ totalSize: number; availableSpace?: number }> {
		try {
			// Calculate total size of files in storage directory
			const files = await readdir(this.config.basePath);
			let totalSize = 0;

			for (const file of files) {
				try {
					const filePath = join(this.config.basePath, file);
					const stats = await stat(filePath);
					if (stats.isFile()) {
						totalSize += stats.size;
					}
				} catch {
					// Skip files that can't be read
				}
			}

			return { totalSize };
		} catch (error) {
			cmsLogger.error('Error getting storage info:', error);
			return { totalSize: 0 };
		}
	}

	/**
	 * Health check - test if we can write to storage
	 */
	async isHealthy(): Promise<boolean> {
		try {
			const testFile = join(this.config.basePath, `health-check-${Date.now()}.tmp`);
			await mkdir(dirname(testFile), { recursive: true });
			await writeFile(testFile, 'health check');
			await unlink(testFile);
			return true;
		} catch (error) {
			cmsLogger.error('Storage health check failed:', error);
			return false;
		}
	}
}
